name: Publish Flipt Private
on:
  push:
  pull_request:
  workflow_dispatch:
  
permissions:
  packages: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          check-latest: true
          cache: true

      - uses: actions/cache@v3
        with:
          path: _tools/
          key: ${{ runner.os }}-go-tools${{ hashFiles('_tools/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-tools-

      - uses: actions/checkout@v3
        with:
          repository: magefile/mage
          path: mage

      - name: Build mage
        working-directory: mage
        run: go run bootstrap.go

      - name: Publish
        working-directory: build
        run: |
          export TAG="$(echo ${GITHUB_SHA} | cut -c -7)"

          echo $TAG

          GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" mage publish:flipt "ghcr.io/flipt-io/flipt-private:$TAG"
